export const PostulacionesDeEjemplo = [
    {
        title:'Algoritmos y Complejidad',
        estado: 'Rechazada',
        Profesor: 'Diego Arroyuelo',
        Contacto: 'DArroyuelo@inf.utfsm.cl',
        Campus: 'San Joaquín',
        Salario: '$64.600',
        HorasLab: '3',
        HorasCorreccion: '10',
        HorasContacto: '2',
    },
    {
        title:'Lenguajes de Programación',
        estado: 'Rechazada',
        Profesor: 'José Luis Martí',
        Contacto: 'jlml@inf.utfsm.cl',
        Campus: 'San Joaquín',
        Salario: '$67.100',
        HorasLab: '0',
        HorasCorreccion: '8',
        HorasContacto: '7',
    },
    {
        title:'Estructuras Discretas',
        estado: 'Aprobada',
        Profesor: 'Claudio Lobos',
        Contacto: 'cucholobos@inf.utfsm.cl',
        Campus: 'San Joaquín',
        Salario: '$59.700',
        HorasLab: '0',
        HorasCorreccion: '15',
        HorasContacto: '0',
    },
    {
        title:'Estructura de Datos',
        estado: 'En espera',
        Profesor: 'Diego Arroyuelo',
        Contacto: 'DArroyuelo@inf.utfsm.cl',
        Campus: 'San Joaquín',
        Salario: '$68.600',
        HorasLab: '3',
        HorasCorreccion: '10',
        HorasContacto: '2',
    },
    {
        title:'Optimización',
        estado: 'Rechazada',
        Profesor: 'Carlos Castro',
        Contacto: 'CCastro@inf.utfsm.cl',
        Campus: 'San Joaquín',
        Salario: '$61.200',
        HorasLab: '0',
        HorasCorreccion: '0',
        HorasContacto: '15',
    },
    {
        title:'Inteligencia Artificial',
        estado: 'Rechazada',
        Profesor: 'Nicolás Rojas',
        Contacto: 'nrojas@inf.utfsm.cl',
        Campus: 'San Joaquín',
        Salario: '$69.420',
        HorasLab: '8',
        HorasCorreccion: '7',
        HorasContacto: '0',
    },
    {
        title:'Base de Datos',
        estado: 'Rechazada',
        Profesor: 'Marcelo Mendoza',
        Contacto: 'mmendoza@inf.utfsm.cl',
        Campus: 'San Joaquín',
        Salario: '$67.100',
        HorasLab: '0',
        HorasCorreccion: '7',
        HorasContacto: '8',
    },
    {
        title:'Sistemas Distribuidos',
        estado: 'En espera',
        Profesor: 'Erika Rosas',
        Contacto: 'tiaerika@inf.utfsm.cl',
        Campus: 'San Joaquín',
        Salario: '$56.800',
        HorasLab: '15',
        HorasCorreccion: '0',
        HorasContacto: '0',
    },
    {
        title:'Sistemas de Gestión',
        estado: 'Aprobada',
        Profesor: 'Luis Hevia',
        Contacto: 'lhevia@inf.utfsm.cl',
        Campus: 'Australia',
        Salario: 'los ODS de la ONU',
        HorasLab: '0',
        HorasCorreccion: '15',
        HorasContacto: '0',
    },
    {
        title:'Aprendizaje Automático',
        estado: 'Rechazada',
        Profesor: 'Ricardo Ñanculef',
        Contacto: 'calcetin@gmail.com',
        Campus: 'Dubai',
        Salario: '$1.234.500',
        HorasLab: '124',
        HorasCorreccion: '45',
        HorasContacto: '0',
    },
    {
        title:'Sistemas Distribuidos',
        estado: 'Aprobada',
        Profesor: 'Erika Rosas',
        Contacto: 'erosas@gmail.com',
        Campus: 'San Joaquin',
        Salario: '$62.500',
        HorasLab: '2',
        HorasCorreccion: '200',
        HorasContacto: '0',
    },
]